@startuml

title Compañía Aseguradora

abstract class Poliza {
  - numeroPoliza: int
  - fechaInicio: Date
  - fechaFin: Date
  + calcularCosto()
  + renovarPoliza()
  + cancelarPoliza()
}

class Cliente {
  - nombre: String
  - apellido: String
  - dni: int
  - telefono: String
  - direccion: String
  - correoElectronico: String
  - vehiculos: List<idVehiculo>

  + contratarPoliza()
  + solicitarGrua()
  + reportarSiniestro()
}

class ProductorSeguro {
  - nombre: String
  - matricula: String
  - clientes: List<dni>
  - polizas: List<numeroPoliza>
  - talleres: List<idTaller>

  + gestionarPoliza()
}

class Vehiculo {
  - idVehiculo: String
  - modelo: String
  - marca: String
  - año: int
  - color: String
  - patente: String
  - kilometraje: int
  - fechaVTV: Date
  - numeroPoliza

  + actualizarKilometraje()
  + verificarVTV()
}

class ServicioDeGrua {
  - idServicioGrua: String
  - fecha: Date
  - ubicacionIncidente: String
  - kilometrajeTraslado: int
  + solicitarServicio()
}

class TallerReparacion {
  - idTaller: String
  - nombre: String
  - direccion: String
  - telefono: String

  + registrarReparacion()
  + abonarReparacion()
}

class Siniestro {
  - idSiniestro: String
  - fecha: Date
  - tipo: String
  - ubicacion: String
  - descripcion: String

  + registrarSiniestro()
}

Cliente "1..*" -- "0..*" Vehiculo
Cliente -- ProductorSeguro
Cliente "1" o-- "0..*" Poliza

Poliza <|-- PolizaDeVida
Poliza <|-- PolizaDeHogar
Poliza <|-- PolizaVehicular

PolizaVehicular -- "1" Vehiculo

ProductorSeguro "1" -- "1..*" Poliza
ProductorSeguro "1..*" -- "1..*" ServicioDeGrua
ProductorSeguro "1..*" -- "1..*" TallerReparacion

TallerReparacion -- Siniestro

@enduml
