@startuml

title Empresa de Transporte

|Cliente|
start
:Registrar Paquete;
:Ingresar Información del Paquete;
:Enviar Información del Paquete;

|EmpresaGestora|
:Validar Información del Paquete;
:Guardar Información del Paquete;
:Asignar Transportista;
:Generar Hoja de Ruta;
:Notificar Transportista;

|Transportista|
:Recibir Hoja de Ruta;
:Iniciar Entrega;

repeat
    :Intentar Entrega;
    if (Entrega Exitosa?) then (yes)
        :Registrar Entrega Exitosa;
        :Notificar Cliente;
        stop
    else (no)
        :Registrar Intento Fallido;
        :Notificar Cliente del Intento Fallido;
    endif
:Programar Nueva Visita;
repeat while (Intentos < 3);

|EmpresaGestora|
:Notificar Cliente para Retirar Paquete;
stop
@enduml
