@startuml Diagrama Caso Uso 3

title Consultar Visitantes Actuales

left to right direction
skinparam packageStyle rectangle

actor Guardia as g
actor Administrador as a

rectangle Sistema {
  usecase "Listar visitantes actuales" as UC1
  usecase "Consultar por DNI o vehículo" as UC2
}


Sistema .. a

g -right- UC1
g -- UC2
a -left- UC1

@enduml
